### ISSUE TITLE
circuit symbols not working

### ISSUE THREAD

**Issue by sriniv1422** [fsmMLK/inkscapeMadeEasy#13]
I have followed  all the procedures you mentioned to use circuit symbols in inkscape. But I still get this error and Iam unable to use it . Can you please suggest how to get around this. 
Traceback (most recent call last):
  File "circuitSymbols.py", line 567, in <module>
    circuit.run()
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/base.py", line 131, in run
    self.save_raw(self.effect())
  File "circuitSymbols.py", line 231, in effect
    [self.voltageColor, alpha] = inkDraw.color.parseColorPicker(so.voltColor, so.colorPickerVolt)
ValueError: too many values to unpack (expected 2)

**Comment by fsmMLK** [comment]
this bug has been fixed.
