### ISSUE TITLE
Inkscape 0.92 -- 64bit on W7 Enterprise

### ISSUE THREAD

**Issue by MikeAnblips** [fsmMLK/inkscapeMadeEasy#2]
I am getting the following error in Python code:

```
Traceback (most recent call last):
  File "circuitSymbols.py", line 5, in <module>
    import inkscapeMadeEasy_Base as inkBase
  File "C:\Users\me\AppData\Roaming\inkscape\extensions\inkscapeMadeEasy_Base.py", line 81
    """
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 142-143: truncated \uXXXX escape
```

**Comment by MikeAnblips** [comment]
Sorry, that is for CircuitSymbols, not directly for MadeEasy
