### ISSUE TITLE
autodoc finds syntax error in documentation

### ISSUE THREAD

**Issue by vanzandtj** [fsmMLK/inkscapeMadeEasy#6]
I downloaded today's .zip file, cd'd to docs/, tried to make the man and info pages, and got a syntax error:

home:/usr/local/src/inkscape/inkscapeMadeEasy-master/docs $ make man info 
sphinx-build -b man -d ../../inkscapeMadeEasy_sphinxBuildDirectory/doctrees   source ../../inkscapeMadeEasy_sphinxBuildDirectory/man
Running Sphinx v1.8.5
making output directory...
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] index                                                                                  
WARNING: autodoc: failed to import module 'inkscapeMadeEasy_Draw'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/usr/local/src/inkscape/inkscapeMadeEasy-master/inkscapeMadeEasy_Draw.py", line 44, in <module>
    import textextLib.textext as textext
  File "/usr/local/src/inkscape/inkscapeMadeEasy-master/textextLib/textext.py", line 121
    except StandardError, e:
                        ^
SyntaxError: invalid syntax

WARNING: autodoc: failed to import module 'inkscapeMadeEasy_Plot'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/usr/local/src/inkscape/inkscapeMadeEasy-master/inkscapeMadeEasy_Plot.py", line 26, in <module>
    import inkscapeMadeEasy_Draw as inkDraw
  File "/usr/local/src/inkscape/inkscapeMadeEasy-master/inkscapeMadeEasy_Draw.py", line 44, in <module>
    import textextLib.textext as textext
  File "/usr/local/src/inkscape/inkscapeMadeEasy-master/textextLib/textext.py", line 121
    except StandardError, e:
                        ^
SyntaxError: invalid syntax

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... inkscapemadeeasy.1 { } 
build succeeded, 2 warnings.

The manual pages are in ../../inkscapeMadeEasy_sphinxBuildDirectory/man.

Build finished. The manual pages are in ../../inkscapeMadeEasy_sphinxBuildDirectory/man.
sphinx-build -b texinfo -d ../../inkscapeMadeEasy_sphinxBuildDirectory/doctrees   source ../../inkscapeMadeEasy_sphinxBuildDirectory/texinfo
Running Sphinx v1.8.5
making output directory...
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [texinfo]: all documents
updating environment: [] 0 added, 1 changed, 0 removed
reading sources... [100%] index                                                                                  
WARNING: autodoc: failed to import module 'inkscapeMadeEasy_Draw'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/usr/local/src/inkscape/inkscapeMadeEasy-master/inkscapeMadeEasy_Draw.py", line 44, in <module>
    import textextLib.textext as textext
  File "/usr/local/src/inkscape/inkscapeMadeEasy-master/textextLib/textext.py", line 121
    except StandardError, e:
                        ^
SyntaxError: invalid syntax

WARNING: autodoc: failed to import module 'inkscapeMadeEasy_Plot'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/usr/local/src/inkscape/inkscapeMadeEasy-master/inkscapeMadeEasy_Plot.py", line 26, in <module>
    import inkscapeMadeEasy_Draw as inkDraw
  File "/usr/local/src/inkscape/inkscapeMadeEasy-master/inkscapeMadeEasy_Draw.py", line 44, in <module>
    import textextLib.textext as textext
  File "/usr/local/src/inkscape/inkscapeMadeEasy-master/textextLib/textext.py", line 121
    except StandardError, e:
                        ^
SyntaxError: invalid syntax

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
processing inkscapeMadeEasy.texi...index 
resolving references...
writing... done
copying images... [100%] ../imagesDocs/samples_01.png                                                            
copying Texinfo support files... /usr/local/src/inkscape/inkscapeMadeEasy_sphinxBuildDirectory/texinfo/Makefile done
build succeeded, 2 warnings.

The Texinfo files are in ../../inkscapeMadeEasy_sphinxBuildDirectory/texinfo.
Run 'make' in that directory to run these through makeinfo
(use 'make info' here to do that automatically).
Running Texinfo files through makeinfo...
make -C ../../inkscapeMadeEasy_sphinxBuildDirectory/texinfo info
make[1]: Entering directory '/usr/local/src/inkscape/inkscapeMadeEasy_sphinxBuildDirectory/texinfo'
makeinfo --no-split -o 'inkscapeMadeEasy.info' 'inkscapeMadeEasy.texi'
make[1]: Leaving directory '/usr/local/src/inkscape/inkscapeMadeEasy_sphinxBuildDirectory/texinfo'
makeinfo finished; the Info files are in ../../inkscapeMadeEasy_sphinxBuildDirectory/texinfo.

**Comment by fsmMLK** [comment]
my sphinx is 1.6.7 and works just fine here. It might be a version sintax change.

**Comment by cocoa1231** [comment]
Can confirm that I'm experiencing this while using inkscapeDimensions as mentioned here -
https://github.com/fsmMLK/inkscapeDimensions/issues/9

Inkscape version 1.0 (1.0+r73+1) on Elementary OS 5.0 based on Ubuntu 18.04
Full error:

```
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp
Traceback (most recent call last):
  File "dimensions.py", line 7, in <module>
    import inkscapeMadeEasy_Draw as inkDraw
  File "/home/elementarycocoa/.config/inkscape/extensions/inkscapeMadeEasy_Draw.py", line 44, in <module>
    import textextLib.textext as textext
  File "/home/elementarycocoa/.config/inkscape/extensions/textextLib/textext.py", line 120
    except StandardError, e:
                        ^
SyntaxError: invalid syntax
```

**Comment by fsmMLK** [comment]
This problem is related to except sintax changed between different python versions.

the most updated version of inkscapeMadeEasy I uploaded today will hopefully solve this issue. However it will take some time for me to update all my plugins.
